apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: prometheus
spec:
  datasources:
    - access: proxy
      editable: true
      isDefault: false
      jsonData:
        timeInterval: 5s
      name: prometheus
      type: prometheus
      url: 'http://prometheus-operated:9090'
      version: 1
  name: manuela-prometheus.yaml
