apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewBuild
  creationTimestamp: "2021-05-10T18:50:08Z"
  generation: 22
  labels:
    app: mymodel
  managedFields:
  - apiVersion: build.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:openshift.io/generated-by: {}
        f:labels:
          .: {}
          f:app: {}
      f:spec:
        f:output:
          f:to:
            .: {}
            f:kind: {}
            f:name: {}
        f:runPolicy: {}
        f:source:
          f:binary: {}
          f:type: {}
        f:strategy:
          f:dockerStrategy:
            .: {}
            f:from:
              .: {}
              f:kind: {}
              f:name: {}
          f:type: {}
        f:triggers: {}
    manager: oc
    operation: Update
    time: "2021-05-10T18:50:08Z"
  - apiVersion: build.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:lastVersion: {}
    manager: openshift-apiserver
    operation: Update
    time: "2021-05-10T18:51:14Z"
  name: mymodel
  namespace: ml-mon
  resourceVersion: "6168399"
  uid: 0e834ea0-399c-4b38-a009-e5faf2051cce
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: mymodel:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: python-36:latest
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: VZVsXcROoncrWqJVlsN8
    type: GitHub
  - generic:
      secret: -xWolMTP0mpcyBUypbZJ
    type: Generic
status:
  lastVersion: 21
