apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: my-service-monitor
    team: opendatahub
  name: my-service-monitor
  namespace: ml-mon
spec:
  endpoints:
  - interval: 30s
    path: /metrics
    port: http
  selector:
    matchLabels:
      app: nvidia-dcgm-exporter
