apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    seldon-app: mymodel-mygroup
    team: opendatahub
  name: mymodel-mygroup
spec:
  endpoints:
  - interval: 30s
    path: /prometheus
    port: http
  selector:
    matchLabels:
      seldon-app: mymodel-mygroup
