{
 "title": "New Prediction Analytics",
 "description": "Prediction Analytics based on original. Changed for Seldon 1.2.2 operator",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "project",
    "query": "label_values(seldon_api_executor_server_requests_seconds_count,namespace)"
   },
   {
    "name": "deployment",
    "query": "label_values(seldon_api_executor_client_requests_seconds_count,deployment_name)"
   },
   {
    "name": "predictor",
    "query": "label_values(seldon_api_executor_client_requests_seconds_count,predictor_name)"
   },
   {
    "name": "version",
    "query": "label_values(seldon_api_executor_client_requests_seconds_count,predictor_version)"
   },
   {
    "name": "model_name",
    "query": "label_values(seldon_api_executor_client_requests_seconds_count,model_name)"
   },
   {
    "name": "model_image",
    "query": "label_values(seldon_api_executor_client_requests_seconds_count,model_image)"
   },
   {
    "name": "model_version",
    "query": "label_values(seldon_api_executor_client_requests_seconds_count,model_version)"
   }
  ]
 },
 "panels": [
  { "title": "Heading", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 22, "x": 0, "y": 1 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>Seldon Deploy Prediction API Dashboard</span>\n</div>"
  },
  { "title": "Global Counts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Global Request Rate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 4 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "round(sum(irate(seldon_api_executor_server_requests_seconds_count[1m])), 0.001)"
    }
   ]
  },
  {
   "title": "Success",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 10, "y": 4 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(seldon_api_executor_server_requests_seconds_count{status!~\"5.*\"}[1m])) / sum(rate(seldon_api_executor_server_requests_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "4xxs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 16, "y": 4 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(seldon_api_executor_server_requests_seconds_count{code=~\"4.*\"}[1m])) "
    }
   ]
  },
  { "title": "API Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Prediction API req/sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 22, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum(rate(seldon_api_executor_server_requests_seconds_count{exported_service=~\"predictions\",namespace=~\"$project\",deployment_name=~\"$deployment\",code=\"200\"}[1m]))by (project_name, deployment_name, deployment_version, exported_service, code),0.0001)",
     "legendFormat": "{{project_name}}/{{deployment_name}}:{{deployment_version}} "
    }
   ]
  },
  { "title": "API Percentiles", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Prediction API Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 22, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(seldon_api_executor_server_requests_seconds_bucket{exported_service=~\"predictions\",namespace=~\"$project\",deployment_name=~\"$deployment\",code=\"200\"}[1m])) by (namespace, deployment_name, exported_service, code,le))",
     "legendFormat": "{{project_name}}/{{deployment_name}} :{{code}} (p50)"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(seldon_api_executor_server_requests_seconds_bucket{exported_service=~\"predictions\",namespace=~\"$project\",deployment_name=~\"$deployment\",code=\"200\"}[1m])) by (namespace, deployment_name, exported_service, code,le))",
     "legendFormat": "{{project_name}}/{{deployment_name}} :{{code}} (p75)"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(seldon_api_executor_server_requests_seconds_bucket{exported_service=~\"predictions\",namespace=~\"$project\",deployment_name=~\"$deployment\",code=\"200\"}[1m])) by (namespace, deployment_name, exported_service, code,le))",
     "legendFormat": "{{project_name}}/{{deployment_name}} :{{code}} (p90)"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(seldon_api_executor_server_requests_seconds_bucket{exported_service=~\"predictions\",namespace=~\"$project\",deployment_name=~\"$deployment\",code=\"200\"}[1m])) by (namespace, deployment_name, exported_service, code,le))",
     "legendFormat": "{{project_name}}/{{deployment_name}} :{{code}} (p99)"
    }
   ]
  },
  { "title": "Predictive Units", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 22, "x": 0, "y": 22 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>Models</span>\n</div>"
  },
  { "title": "Model Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 }, "repeat": "model_image" },
  {
   "title": "Reqs/sec to $model_image",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(seldon_api_executor_client_requests_seconds_count{model_image=~\"$model_image\",namespace=~\"$project\",deployment_name=~\"$deployment\",predictor_name=~\"$predictor\",predictor_version=~\"$version\"}[1m])) by (namespace,deployment_name,predictor_name,predictor_version,model_image,model_version,model_name)",
     "legendFormat": "{{project_name}}/{{deployment_name}}:{{deployment_version}}/{{predictor_name}}:{{predictor_version}} ({{model_name}} {{model_image}} : {{model_version}})"
    }
   ]
  },
  {
   "title": "$model_image Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(seldon_api_executor_client_requests_seconds_bucket{exported_service=~\".*predict\",model_image=~\"$model_image\",namespace=~\"$project\",deployment_name=~\"$deployment\",predictor_name=~\"$predictor\",predictor_version=~\"$version\"}[1m])) by (namespace,deployment_name,predictor_name,predictor_version,model_name,model_image,model_version,le))",
     "legendFormat": "{{project_name}}/{{deployment_name}}:{{deployment_version}}/{{predictor_name}}:{{predictor_version}} {{model_name}}: {{model_version}} (p50)"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(seldon_api_executor_client_requests_seconds_bucket{exported_service=~\".*predict\",model_image=~\"$model_image\",namespace=~\"$project\",deployment_name=~\"$deployment\",predictor_name=~\"$predictor\",predictor_version=~\"$version\"}[1m])) by (namespace,deployment_name,predictor_name,predictor_version,model_name,model_image,model_version,le))",
     "legendFormat": "{{project_name}}/{{deployment_name}}:{{deployment_version}}/{{predictor_name}}:{{predictor_version}} {{model_name}} : {{model_version}} (p75)"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(seldon_api_executor_client_requests_seconds_bucket{exported_service=~\".*predict\",model_image=~\"$model_image\",namespace=~\"$project\",deployment_name=~\"$deployment\",predictor_name=~\"$predictor\",predictor_version=~\"$version\"}[1m])) by (namespace,deployment_name,predictor_name,predictor_version,model_name,model_image,model_version,le))",
     "legendFormat": "{{project_name}}/{{deployment_name}}:{{deployment_version}}/{{predictor_name}}:{{predictor_version}} {{model_name}}: {{model_version}} (p90)"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(seldon_api_executor_client_requests_seconds_bucket{exported_service=~\".*predict\",model_image=~\"$model_image\",namespace=~\"$project\",deployment_name=~\"$deployment\",predictor_name=~\"$predictor\",predictor_version=~\"$version\"}[1m])) by (namespace,deployment_name,predictor_name,predictor_version,model_name,model_image,model_version,le))",
     "legendFormat": "{{project_name}}/{{deployment_name}}:{{deployment_version}}/{{predictor_name}}:{{predictor_version}} {{model_name}}: {{model_version}} (p95)"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(seldon_api_executor_client_requests_seconds_bucket{exported_service=~\".*predict\",model_image=~\"$model_image\",namespace=~\"$project\",deployment_name=~\"$deployment\",predictor_name=~\"$predictor\",predictor_version=~\"$version\"}[1m])) by (namespace,deployment_name,predictor_name,predictor_version,model_name,model_image,model_version,le))",
     "legendFormat": "{{project_name}}/{{deployment_name}}:{{deployment_version}}/{{predictor_name}}:{{predictor_version}} {{model_name}}: {{model_version}} (p99)"
    }
   ]
  },
  { "title": "Model Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Reqs/sec to $model_image",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(seldon_api_executor_client_requests_seconds_count{model_image=~\"$model_image\",namespace=~\"$project\",deployment_name=~\"$deployment\",predictor_name=~\"$predictor\",predictor_version=~\"$version\"}[1m])) by (namespace,deployment_name,predictor_name,predictor_version,model_image,model_version,model_name)",
     "legendFormat": "{{project_name}}/{{deployment_name}}:{{deployment_version}}/{{predictor_name}}:{{predictor_version}} ({{model_name}} {{model_image}} : {{model_version}})"
    }
   ]
  },
  {
   "title": "$model_image Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(seldon_api_executor_client_requests_seconds_bucket{exported_service=~\".*predict\",model_image=~\"$model_image\",namespace=~\"$project\",deployment_name=~\"$deployment\",predictor_name=~\"$predictor\",predictor_version=~\"$version\"}[1m])) by (namespace,deployment_name,predictor_name,predictor_version,model_name,model_image,model_version,le))",
     "legendFormat": "{{project_name}}/{{deployment_name}}:{{deployment_version}}/{{predictor_name}}:{{predictor_version}} {{model_name}}: {{model_version}} (p50)"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(seldon_api_executor_client_requests_seconds_bucket{exported_service=~\".*predict\",model_image=~\"$model_image\",namespace=~\"$project\",deployment_name=~\"$deployment\",predictor_name=~\"$predictor\",predictor_version=~\"$version\"}[1m])) by (namespace,deployment_name,predictor_name,predictor_version,model_name,model_image,model_version,le))",
     "legendFormat": "{{project_name}}/{{deployment_name}}:{{deployment_version}}/{{predictor_name}}:{{predictor_version}} {{model_name}} : {{model_version}} (p75)"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(seldon_api_executor_client_requests_seconds_bucket{exported_service=~\".*predict\",model_image=~\"$model_image\",namespace=~\"$project\",deployment_name=~\"$deployment\",predictor_name=~\"$predictor\",predictor_version=~\"$version\"}[1m])) by (namespace,deployment_name,predictor_name,predictor_version,model_name,model_image,model_version,le))",
     "legendFormat": "{{project_name}}/{{deployment_name}}:{{deployment_version}}/{{predictor_name}}:{{predictor_version}} {{model_name}}: {{model_version}} (p90)"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(seldon_api_executor_client_requests_seconds_bucket{exported_service=~\".*predict\",model_image=~\"$model_image\",namespace=~\"$project\",deployment_name=~\"$deployment\",predictor_name=~\"$predictor\",predictor_version=~\"$version\"}[1m])) by (namespace,deployment_name,predictor_name,predictor_version,model_name,model_image,model_version,le))",
     "legendFormat": "{{project_name}}/{{deployment_name}}:{{deployment_version}}/{{predictor_name}}:{{predictor_version}} {{model_name}}: {{model_version}} (p95)"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(seldon_api_executor_client_requests_seconds_bucket{exported_service=~\".*predict\",model_image=~\"$model_image\",namespace=~\"$project\",deployment_name=~\"$deployment\",predictor_name=~\"$predictor\",predictor_version=~\"$version\"}[1m])) by (namespace,deployment_name,predictor_name,predictor_version,model_name,model_image,model_version,le))",
     "legendFormat": "{{project_name}}/{{deployment_name}}:{{deployment_version}}/{{predictor_name}}:{{predictor_version}} {{model_name}}: {{model_version}} (p99)"
    }
   ]
  }
 ]
}