apiVersion: v1
kind: ConfigMap
metadata:
  name: developer-jupyterhub-sizes
  labels:
    jupyterhub: singleuser-profiles
data:
  jupyterhub-singleuser-profiles.yaml: |
      sizes:
      - name: XX-Large-Memory
        resources:
          requests:
            memory: 2Gi
            cpu: 2
          limits:
            memory: 16Gi
            cpu: 4
